version: '3'

networks:
  konsultant:
    external: false

services:
  web:
    build: .
    container_name: konsultant_web
    volumes:
      - sitestatics:/app/static_assets/
      - sitemedias:/app/medias/
    depends_on:
      - db
    networks:
      - konsultant

  db:
    image: "postgres:latest"
    container_name: konsultant_db
    environment:
      POSTGRES_PASSWORD: mypassword
    networks:
      - konsultant
    volumes:
      - pgdb:/var/lib/postgresql/data

  nginx:
    image: nginx:1.19-alpine
    container_name: konsultant_nginx
    volumes:
      - sitestatics:/home/app/web/static_assets
      - sitemedias:/home/app/web/medias
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - konsultant
    ports:
      - '80:80'

volumes:
  pgdb:
  sitestatics:
  sitemedias:
